import 'package:food_app/podo/food.dart';
String image= "assets/food";
List<Food> foods = [
  Food(
    name: "Lemon Ice Tea",
    increment: 1,
    isSpecial: true,
    price: 130,
    image: "${image}8.jpeg",
  ),
  Food(
    name: "Peach Ice Tea",
    increment: 1,
    isSpecial: true,
    price: 150,
    image: "${image}1.jpeg",
  ),
  Food(
    name: "Mojito Ice Tea",
    increment: 1,
    isSpecial: true,
    price: 160,
    image: "${image}2.jpeg",
  ),
  Food(
    name: "Mint Lemonade",
    increment: 1,
    isSpecial: true,
    price: 160,
    image: "${image}3.jpeg",
  ),
  Food(
    name: "Peach Lemonade",
    increment: 1,
    isSpecial: true,
    price: 150,
    image: "${image}4.jpeg",
  ),
  Food(
    name: "Strawberry Lemonade",
    increment: 1,
    isSpecial: true,
    price: 150,
    image: "${image}5.jpeg",
  ),
  Food(
    name: "English Breakfast Tea",
    increment: 1,
    isSpecial: true,
    price: 50,
    image: "${image}6.jpeg",
  ),
  Food(
    name: "Earl Grey Tea",
    increment: 1,
    isSpecial: true,
    price: 50,
    image: "${image}7.jpeg",
  ),
  Food(
      name: "Flavoured Tea",
      increment: 1,
      isSpecial: true,
      price: 50,
      image: "${image}8.jpeg",
      variety: ['Peach', 'strawberry', 'chocolate']),
  Food(
    name: "Hot Lemon With Honey",
    increment: 1,
    isSpecial: true,
    price: 50,
    image: "${image}9.jpeg",
  ),
  Food(
    name: "Veg Burger",
    increment: 1,
    isSpecial: true,
    price: 120,
    image:"${image}10.jpeg",
  ),
  Food(
    name: "Veg Burger",
    increment: 1,
    isSpecial: true,
    price: 150,
    image: "${image}10.jpeg",
  ),
  Food(
    name: "Additional cheese",
    increment: 1,
    isSpecial: true,
    price: 50,
    image: "${image}10.jpeg",
  ),
  Food(
    name: "Egg roll",
    increment: 1,
    isSpecial: true,
    price: 120,
    image: "${image}10.jpeg",
  ),
  Food(
    name: "Egg Chicken roll",
    increment: 1,
    isSpecial: true,
    price: 150,
    image:  "${image}10.jpeg",
  ),
  Food(
    name: "Egg Tuna roll",
    increment: 1,
    isSpecial: true,
    price: 150,
    image: "${image}10.jpeg",
  ),
  Food(
    name: "Veg sandwich",
    increment: 1,
    isSpecial: true,
    price: 150,
    image: "${image}10.jpeg",
  ),
  Food(
    name: "Tuna sandwich",
    increment: 1,
    isSpecial: true,
    price: 150,
    image: "${image}10.jpeg",
  ),
  Food(
    name: "Chicken sandwich",
    increment: 1,
    isSpecial: true,
    price: 150,
    image: "${image}10.jpeg",
  ),
  Food(
    name: "Club sandwich",
    increment: 1,
    isSpecial: true,
    price: 200,
    image: "${image}10.jpeg",
  ),
  Food(
      name: "Buff kothey Momo",
      increment: 1,
      unit: "plate",
      isSpecial: true,
      price: 120,
      image: "${image}10.jpeg",
      variety: ['Peach', 'strawberry', 'chocolate']),
  Food(
    name: "Chicken kothey Momo",
    increment: 1,
    unit: "plate",
    isSpecial: true,
    price: 150,
    image: "${image}10.jpeg",
  ),
];